### ISSUE TITLE
Security analysis shows many CVE's

### ISSUE THREAD

**Issue by christopherraa** [Perl/docker-perl#105]
A client did a security analysis of the image tagged `perl:5.32.0` and found quite a serious amount of high/critical CVE's being present. I have attached the report to this issue.

[perl-5.32.0-analysis.txt](https://github.com/Perl/docker-perl/files/6590819/perl-5.32.0-analysis.txt)

Awaiting analysis of `perl:5.34.0-slim` to see how that compares. Will upload that when ready.

In my opinion it is important that this is looked into.

**Comment by yoho582** [comment]
Hi, here is analysis of perl:5.34.0-slim

[perl_34_slim.txt](https://github.com/Perl/docker-perl/files/6591168/perl_34_slim.txt)

**Comment by zakame** [comment]
Hi @christopherraa and @yoho582, thanks for the reports!

I'm quite aware of this, as Docker Hub used to previously do vulnerability scanning for public images as well, until they made this feature available only to pro/team plans :crying_cat_face:.  The core source of these issues arise from our use of base images _without_ upgrading the individual package dependencies which may pull in new security updates (e.g. we `apt-get update` for installing _new_ dependencies on `slim` variants, but do not `apt-get upgrade` on any variant.)

I'm sure @tianon or @yosifkit can tell more, but I believe the general response for this is that we'd encourage image users to do this `apt-get upgrade` step on their own derived image creations, as they would usually be in a better position to both find updated security packages as well as ensure that they comply to their own security requirements beyond Docker image scanning - see for example https://github.com/docker-library/official-images/issues/4315.  That said, for any CVEs directly affecting our build of Perl here (as well as for `cpanm`, which is the only other CPAN tool we pull beyond those available in Perl core) we will indeed update/upgrade from here as necessary (including putting Devel-PatchPerl compatible patches.)

**Comment by christopherraa** [comment]
Thank you for a thorough explaination of your stance on this issue. While I agree that users of the image always should do an upgrade in their own build pipelines I still would like for the base image to be as "up to date" as possible. For one it might helt keep the users who still don't know that they _should_ upgrade on their side as well. It is also an issue of appearance: it is always better to have fewer than more vulnerabilities, especially these base images feature in comparisons by security analysts etc. Though the former issue about keeping users safe is the thing I am most concerned about.

In any case: thank you for taking the time to respond. I am glad that you are aware of the issue.

**Comment by zakame** [comment]
Also for reference, #46 and #57.

Indeed, having the base image we depend for docker-perl as up-to-date as possible for fewer visible issues to end users is a good point - for this, we are actually under the assumption the the base image is routinely updated for these security fixes, as noted in https://github.com/docker-library/official-images#library-definition-files and https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves.  Perhaps we might need to challenge that assumption again, since this issue isn't really limited to just docker-perl at all - Python has https://github.com/docker-library/python/issues/593 for instance.

OTOH, for users or organizations that require even higher scrutiny than rebuilds or updates that Docker Hub can provide in a timely manner, I recommend them actually forking the Dockerfiles we make available here and building their own versions of the images, altering their base `buildpack-deps` or `debian` image as needed to one that is more suitable for their security and compatibility requirements - I've made a similar recommendation before in #79, perhaps this can be made even more visible.

**Comment by yosifkit** [comment]
Details on Official-Images as a whole:

>We strive to publish updated images at least monthly for Debian and Ubuntu. We also rebuild earlier if there is a critical security need [...] These refreshed base images also means that any other image in the Official Images program that is `FROM` them will also be rebuilt
>
>\- https://github.com/docker-library/faq/#why-does-my-security-scanner-show-that-an-image-has-cves
