### ISSUE TITLE
Avoid sha1 for consistency check

### ISSUE THREAD

**Issue by diocles** [Perl/docker-perl#12]
SHA-1 is broken, so it would be nice to use 'sha256sum' or higher for verifying that we have downloaded the correct binary!

Thanks,

**Comment by PeterMartini** [comment]
The primary reason I chose this check was because it's what is announced in the official release notes, which makes it a choice between verifying against the announced but broken SHA-1 or an unannounced SHA-256.  In the longer term, I'll see about changing the Perl 5 release managers notes to use sha256sum for this purpose, and in the short term I'm willing to generate a SHA-256 some for each version with a note that the officially announced hash is only SHA-1.

**Comment by zakame** [comment]
@diocles just for the record, can you cite references on SHA-1 being broken?

**Comment by diocles** [comment]
Very happy to - it was "broken" in 2005, but it's only recently that e.g. SSL certs have been moving away from it:

- https://www.schneier.com/blog/archives/2005/02/sha1_broken.html
- http://googleonlinesecurity.blogspot.co.uk/2014/09/gradually-sunsetting-sha-1.html

**Comment by PeterMartini** [comment]
So, yeah: https://sites.google.com/site/itstheshappening/

**Comment by diocles** [comment]
@PeterMartini Although the release announcements still use SHA1, I've noticed the sha256 hashes are published next to the tarballs, on the mirror, e.g.: http://www.cpan.org/src/5.0/perl-5.25.3.tar.gz.sha256.txt

Maybe there's scope to automate fetching the sha256 in generate.pl?  Depends how you feel about it.

**Comment by diocles** [comment]
@PeterMartini Obligatory ping following the first public collision attack. :)

https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html

**Comment by zakame** [comment]
Thanks, I'm preparing a PR for this as well as making a `perl:5.24.1` image.
