### ISSUE TITLE
`$Config{vendorlib}` unset?

### ISSUE THREAD

**Issue by rysiekpl** [Perl/docker-perl#32]
Running `perl -MConfig -e 'print $Config{vendorlib}'` in the container returns an empty string. It should return a path.

**Comment by zakame** [comment]
Hi @rysiekpl, thanks for the report!

Yep, I think @Perl/docker doesn't define a `vendorlib` upon building Perl for Docker, as `vendorlib` is normally used mainly by OS distributions to allow them to install their Perl packages in a location separate from `sitelib` and `privlib`.

I checked on https://github.com/occrp/kuvert/commit/f8638c9a2befade93abd888ff5757fe652754fc9; since you're installing a module, you can use `sitelib` instead of `vendorlib`; I don't recommend using `$INC[0]` because that will usually prefer the XS path first (e.g. `/usr/local/lib/perl5/site_perl/5.24.1/x86_64-linux`) which may not be what you want.

Adding `Configure` settings for `vendorlib` should be easy enough though, so let me put up a PR here that we can merge in later.  Thanks again!

**Comment by rysiekpl** [comment]
Good suggestion, thanks!
